#!/bin/bash

DEPLOY_MODE=spin_and_config
CLUSTER_NAMES=(austin-spark-cluster)

PEM_NAME=sparklab-west-2
PURCHASE_TYPE=spot #spot or on_demand
REGION=us-west-2
AZ=us-west-2a
NUM_INSTANCES=20
SECURITY_GROUP=open
INSTANCE_TYPE=m4.xlarge
EBS_SIZE=500
PRICE=0.25
AMI=ami-f30b1c92  # Spark 1.4.1 with Hadoop 2.7.1 us-west-2

if [ "$DEPLOY_MODE" == "spin" ] || [ "$DEPLOY_MODE" == "spin_and_config" ]; then
  for CLUSTER_NAME in ${CLUSTER_NAMES[@]}; do
    echo "spinning up $CLUSTER_NAME..."
    time ./spin_up -u $PURCHASE_TYPE -r $REGION -z $AZ -c $CLUSTER_NAME -i $PEM_NAME -n $NUM_INSTANCES -s $SECURITY_GROUP -t $INSTANCE_TYPE -e $EBS_SIZE -p $PRICE -a $AMI &
    echo -e "\n"
  done
  wait
fi

if [ "$DEPLOY_MODE" == "config" ] || [ "$DEPLOY_MODE" == "spin_and_config" ]; then
  for CLUSTER_NAME in ${CLUSTER_NAMES[@]}; do
    echo "configuring $CLUSTER_NAME..."
    time ./config_ami $PEM_NAME $CLUSTER_NAME &
    echo -e "\n"
  done
fi
