#!/bin/bash

CLUSTER_NAME=$1
echo "                HDFS running at : http://$(head -n 1 tmp/$CLUSTER_NAME/master_public_dns.txt):50070"
echo "                YARN running at : http://$(head -n 1 tmp/$CLUSTER_NAME/master_public_dns.txt):8088"
echo "          JobHistory running at : http://$(head -n 1 tmp/$CLUSTER_NAME/master_public_dns.txt):19888"
echo "    Spark Standalone running at : http://$(head -n 1 tmp/$CLUSTER_NAME/master_public_dns.txt):8080"
echo "Spark Application UI running at : http://$(head -n 1 tmp/$CLUSTER_NAME/master_public_dns.txt):4040"


