#!/bin/bash

PEM_NAME=$1
CLUSTER_NAME=$2

SSH/setup_passwordless_ssh.sh ~/.ssh/$PEM_NAME.pem $CLUSTER_NAME

./pass_aws_cred ~/.ssh/$PEM_NAME.pem $CLUSTER_NAME

config/Hadoop/setup_cluster.sh ~/.ssh/$PEM_NAME.pem $CLUSTER_NAME
config/Hive/setup_cluster.sh ~/.ssh/$PEM_NAME.pem $CLUSTER_NAME

config/Spark/setup_cluster.sh ~/.ssh/$PEM_NAME.pem $CLUSTER_NAME

config/Zeppelin/setup_cluster.sh ~/.ssh/$PEM_NAME.pem $CLUSTER_NAME

config/Tachyon/setup_cluster.sh ~/.ssh/$PEM_NAME.pem $CLUSTER_NAME

./create_cred $PEM_NAME $CLUSTER_NAME

echo "                HDFS running at : http://$(head -n 1 tmp/$CLUSTER_NAME/master_public_dns.txt):50070"
echo "                YARN running at : http://$(head -n 1 tmp/$CLUSTER_NAME/master_public_dns.txt):8088"
echo "          JobHistory running at : http://$(head -n 1 tmp/$CLUSTER_NAME/master_public_dns.txt):19888"
echo "    Spark Standalone running at : http://$(head -n 1 tmp/$CLUSTER_NAME/master_public_dns.txt):8080"
echo "Spark Application UI running at : http://$(head -n 1 tmp/$CLUSTER_NAME/master_public_dns.txt):4040"


