#!/bin/bash

PEM_NAME=$1
INSTANCE_NAME=$2

cp ~/.ssh/$PEM_NAME.pem sparklab tmp/$INSTANCE_NAME
head -n 1 tmp/$INSTANCE_NAME/public_dns > tmp/$INSTANCE_NAME/master_public_dns.txt

cd tmp
tar zcvf $INSTANCE_NAME.tar.gz $INSTANCE_NAME
cp $INSTANCE_NAME.tar.gz ../DataLabs
cd ..

