#!/bin/bash

CLUSTER_NAME=$1
SRC=$2
DEST=$3

if [ ! -d tmp/$CLUSTER_NAME ]; then
    echo "cluster does not exist! please run fetch_instances.py first." && exit 1
fi

scp -r -i tmp/$CLUSTER_NAME/*.pem ubuntu@$(head -n 1 tmp/$CLUSTER_NAME/master_public_dns.txt):$SRC $DEST
