#!/bin/bash

# check input arguments
if [ "$#" -ne 3 ]; then
  echo "Please specify cluster name, source and destination" && exit 1
fi

CLUSTER_NAME=$1
SRC=$2
DEST=$3

if [ ! -d tmp/$CLUSTER_NAME ]; then
    echo "cluster does not exist! please run ec2fetch first." && exit 1
fi

scp -r -i tmp/$CLUSTER_NAME/*.pem ubuntu@$(head -n 1 tmp/$CLUSTER_NAME/public_dns):$SRC $DEST
