#!/bin/bash

# check input arguments
if [ "$#" -ne 2 ]; then
    echo "Please specify region and cluster name" && exit 1
fi

REGION=$1
CLUSTER_NAME=$2

PEG_ROOT=$(dirname "${BASH_SOURCE}")

source ${PEG_ROOT}/ec2util.sh

mkdir -p ${PEG_ROOT}/tmp/${CLUSTER_NAME}

store_public_dns ${CLUSTER_NAME}
store_hostnames ${CLUSTER_NAME}
store_pemkey ${CLUSTER_NAME}
describe_cluster ${CLUSTER_NAME}

