#!/bin/bash

# check input arguments
if [ "$#" -ne 2 ]; then
    echo "Please specify cluster name and technology to install" && exit 1
fi

CLUSTER_NAME=$1
TECHNOLOGY=$2

if [ ! -d tmp/$CLUSTER_NAME ]; then
    echo "cluster does not exist! please run ec2fetch first." && exit 1
fi

MASTER_DNS=$(head -n 1 tmp/$CLUSTER_NAME/public_dns)
PEMLOC=tmp/$CLUSTER_NAME/*.pem
DEP_ROOT_FOLDER=/usr/local/

check_remote_folder () {
  ssh -i $PEMLOC ubuntu@$MASTER_DNS bash -c "'
    if [ -d $1 ]; then
      echo "installed"
    else
      echo "missing"
    fi
  '"
}

install_tech () {
  if [ -z "$DEP" ]; then
    echo "Installing $TECHNOLOGY on $CLUSTER_NAME"
    install/cluster_download $PEMLOC $CLUSTER_NAME $TECHNOLOGY
    config/$TECHNOLOGY/setup_cluster.sh $PEMLOC $CLUSTER_NAME
  else
    INSTALLED=$(check_remote_folder $DEP_ROOT_FOLDER$DEP)
    if [ "$INSTALLED" = "installed" ]; then
      DEP=(${DEP[@]:1})
      echo $DEP
      install_tech
    else
      echo "$DEP is not installed in $DEP_ROOT_FOLDER"
      echo "Please install $DEP and then proceed with $TECHNOLOGY"
      echo "./ec2install $PEMLOC $CLUSTER_NAME $DEP"
      exit 1
    fi
  fi
}

get_dependencies () {
  while read line; do
    KEY_RAW=$(echo $line | awk '{print $1}')
    KEY=${KEY_RAW%?}
    VALUE=$(echo $line | awk '{print $2}')
    if [ "$KEY" == "$TECHNOLOGY" ]; then
      if [ -z $VALUE ]; then
        DEP=()
        break
      else
        DEP_RAW=${VALUE/,/ }
        DEP=($DEP_RAW)
      fi
    fi
  done < dependencies.txt
}

case $TECHNOLOGY in
  aws)
    echo "Passing AWS credentials to $CLUSTER_NAME"
    config/pass_aws_cred $PEMLOC $CLUSTER_NAME
    ;;
  environment)
    echo "Setting up base environment packages on $CLUSTER_NAME"
    install/environment/install_env_cluster.sh $PEMLOC $CLUSTER_NAME
    ;;
  cassandra|elasticsearch|flink|hadoop|hbase|hive|kafka|kibana|opscenter|pig|presto|redis|spark|storm|tachyon|zookeeper)
    get_dependencies
    install_tech
    ;;
  ssh)
    echo "Setting up passwordless SSH on $CLUSTER_NAME"
    config/ssh/setup_passwordless_ssh.sh $PEMLOC $CLUSTER_NAME
    ;;
  zeppelin)
    echo "Installing Zeppelin on Master Node in $CLUSTER_NAME"
    install/zeppelin/install_zeppelin_cluster.sh $PEMLOC $CLUSTER_NAME
    config/zeppelin/setup_cluster.sh $PEMLOC $CLUSTER_NAME
    ;;
  *)
    echo "Invalid technology to install."; exit 1 ;;
esac

