#!/bin/bash

# check input arguments
if [ "$#" -ne 3 ]; then
    echo "Please specify region, current cluster name, and new cluster name" && exit 1
fi

REGION=$1
CLUSTER_NAME=$2
NEW_CLUSTER_NAME=$3

cd $(dirname "${BASH_SOURCE}")

python util/retag.py $REGION $CLUSTER_NAME $NEW_CLUSTER_NAME

./ec2fetch $REGION $NEW_CLUSTER_NAME

