#!/bin/bash

# check input arguments
if [ "$#" -ne 1 ]; then
  echo "Please specify instance template json file" && exit 1
fi

TEMPLATE_PATH=$1

if [ ! -f $TEMPLATE_PATH ]; then
  echo "Template file $TEMPLATE_PATH does not exist" && exit 1
fi

python util/spin_up.py $TEMPLATE_PATH
