#!/bin/bash

# check input arguments
if [ "$#" -ne 2 ]; then
  echo "Please specify region and instance template json file" && exit 1
fi

REGION=$1
TEMPLATE_PATH=$2

if [ ! -f $TEMPLATE_PATH ]; then
  echo "Template file $TEMPLATE_PATH does not exist" && exit 1
fi

PEG_ROOT=$(dirname "${BASH_SOURCE}")

source ${PEG_ROOT}/util.sh

set_launch_config ${TEMPLATE_PATH}
run_instances

