#!/bin/bash

# check input arguments
if [ "$#" -ne 2 ]; then
  echo "Please specify region and cluster name" && exit 1
fi

REGION=$1
CLUSTER_NAME=$2

BLU='\033[0;34m'
NC='\033[0m'

if [ ! -d tmp/$CLUSTER_NAME ]; then
  echo "cluster does not exist! please run ec2fetch first." && exit 1
fi

echo -e "Are you sure you want to terminate ${BLU}$CLUSTER_NAME${NC}?"
echo "$(cat tmp/$CLUSTER_NAME/public_dns)"
echo -n "[y/n]: "
read RESPONSE

case $RESPONSE in
  n)
    exit 1
    ;;
  y)
    python util/spin_dn.py $REGION $(cat tmp/$CLUSTER_NAME/public_dns)
    ;;
  *)
    echo "respond with y or n."
    exit 1
    ;;
esac

