#!/bin/bash

# check input arguments
if [ "$#" -ne 2 ]; then
    echo "Please specify cluster name and technology" && exit 1
fi

CLUSTER_NAME=$1
TECHNOLOGY=$2

cd $(dirname "${BASH_SOURCE}")

if [ ! -d tmp/$CLUSTER_NAME ]; then
    echo "cluster does not exist! please run ec2fetch first." && exit 1
fi

MASTER_DNS=$(head -n 1 tmp/$CLUSTER_NAME/public_dns)
PEMLOC=tmp/$CLUSTER_NAME/*.pem
ROOT_FOLDER=/usr/local/

PUBLIC_DNS=()
while read line; do
  PUBLIC_DNS+=(${line})
done < tmp/${CLUSTER_NAME}/public_dns

check_remote_folder () {
  ssh -i $PEMLOC ubuntu@$MASTER_DNS bash -c "'
    if [ -d $1 ]; then
      echo "installed"
    else
      echo "missing"
    fi
  '"
}

uninstall_tech () {
  INSTALLED=$(check_remote_folder ${ROOT_FOLDER}${TECHNOLOGY})
  if [ "$INSTALLED" = "installed" ]; then
    ./ec2service ${CLUSTER_NAME} ${TECHNOLOGY} stop
    for dns in ${PUBLIC_DNS[@]}; do
      echo ${dns}
      ssh -i ${PEMLOC} ubuntu@${dns} bash -c "'
        sudo rm -rf /usr/local/${TECHNOLOGY}
        sed -i \"/$(echo ${TECHNOLOGY} | tr a-z A-Z)/d\" ~/.profile
      '"
    done
  else
    echo "${TECHNOLOGY} is not installed in $ROOT_FOLDER"
    exit 1
  fi
}

case $TECHNOLOGY in
  cassandra|elasticsearch|flink|hadoop|hbase|hive|kafka|kibana|opscenter|pig|presto|redis|spark|storm|tachyon|zeppelin|zookeeper)
    uninstall_tech
    ;;
  *)
    echo -e "Invalid technology to uninstall."; exit 1 ;;
esac
