#!/bin/bash
# Work in progress...
# refactor config scripts to operate in M-W, M-less, and M-only modes
# generalize for all installations

PEGASUS_ROOT=$(dirname "${BASH_SOURCE}")/..

function read_file_to_array {
  while read line; do
    $1+=(${line})
  done < $2
}

# check input arguments
if [ "$#" -ne 2 ]; then
  echo "Please specify pem-key location and cluster name!" && exit 1
fi

PEMLOC=$1
CLUSTER_NAME=$2

# check if pem-key location is valid
if [ ! -f ${PEMLOC} ]; then
  echo "pem key does not exist!" && exit 1
fi

HOSTNAMES=()
HOSTNAME_PATH=${PEGASUS_ROOT}/tmp/${CLUSTER_NAME}/hostnames
read_file_to_array ${HOSTNAMES} ${$HOSTNAME_PATH}

PUBLIC_DNS=()
PUBLIC_DNS_PATH=${PEGASUS_ROOT}/tmp/${CLUSTER_NAME}/public_dns
read_file_to_array ${HOSTNAMES} ${$HOSTNAME_PATH}

MASTER_HOSTNAME
WORKER_HOSTNAME

MASTER_PRIVATE_IP
WORKER_PRIVATE_IP

MASTER_PUBLIC_DNS
WORKER_PUBLIC_DNS

MASTER_PUBLIC_IP
WORKER_PUBLIC_IP
