#!/bin/bash

# check input arguments
if [ "$#" -ne 2 ]; then
  echo "Please specify the pem-key location and cluster name" && exit 1
fi

PEMLOC=$1
CLUSTER_NAME=$2

# check if pem-key location is valid
if [ ! -f $PEMLOC ]; then
  echo "pem-key does not exist!" && exit 1
fi

if [ ! -d tmp/$CLUSTER_NAME ]; then
  echo "cluster does not exist!" && exit 1
fi

while read PUBLIC_DNS; do
  echo $PUBLIC_DNS
  ssh -o "StrictHostKeyChecking no" -n -i $PEMLOC ubuntu@$PUBLIC_DNS 'echo -e "export AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID'\nexport AWS_SECRET_ACCESS_KEY='$AWS_SECRET_ACCESS_KEY'" >> ~/.profile' &
done < tmp/$CLUSTER_NAME/public_dns

wait

