#!/bin/bash

# check input arguments
if [ "$#" -ne 1 ]; then
  echo "Please specify the cluster name" && exit 1
fi

PEG_ROOT=$(dirname ${BASH_SOURCE})/..
source ${PEG_ROOT}/util.sh

CLUSTER_NAME=$1

PUBLIC_DNS=$(fetch_cluster_public_dns ${CLUSTER_NAME})

cmd='echo -e "export AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID'\nexport AWS_SECRET_ACCESS_KEY='$AWS_SECRET_ACCESS_KEY'\nexport AWS_DEFAULT_REGION='$AWS_DEFAULT_REGION'" >> ~/.profile'
for dns in ${PUBLIC_DNS}; do
  echo ${dns}
  run_cmd_on_node ${dns} ${cmd} &
done

wait

