#!/bin/bash

# check input arguments
if [ "$#" -ne 2 ]; then
    echo "Please specify cluster name, and technology!" && exit 1
fi

PEG_ROOT=$(dirname ${BASH_SOURCE})/..

source ${PEG_ROOT}/util.sh

# get input arguments [aws region, pem-key location]
CLUSTER_NAME=$1
TECHNOLOGY=$2

PUBLIC_DNS=$(fetch_cluster_public_dns ${CLUSTER_NAME})

script="${PEG_ROOT}/install/download_tech"
args="${TECHNOLOGY}"

for dns in ${PUBLIC_DNS}; do
  run_script_on_node ${dns} ${script} ${args} &
done

wait

echo "${TECHNOLOGY} installed!"
