#!/bin/bash

# Copyright 2015 Insight Data Science
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# check input arguments
if [ "$#" -ne 3 ]; then
    echo "Please specify cluster name, technology and mode (cluster or single)!" && exit 1
fi

PEG_ROOT=$(dirname ${BASH_SOURCE})/..

source ${PEG_ROOT}/util.sh

# get input arguments [aws region, pem-key location]
CLUSTER_NAME=$1
TECHNOLOGY=$2
MODE=$3

case ${MODE} in 
  single)
    PUBLIC_DNS=$(fetch_public_dns_of_node_in_cluster ${CLUSTER_NAME} 1)
    ;;

  cluster)
    PUBLIC_DNS=$(fetch_cluster_public_dns ${CLUSTER_NAME})
    ;;
esac

script="${PEG_ROOT}/install/download_tech"
args="${TECHNOLOGY}"

for dns in ${PUBLIC_DNS}; do
  echo -e "${color_yellow}Checking node ${dns}${color_norm}"
  run_script_on_node ${dns} ${script} ${args} &
done

wait

echo "${TECHNOLOGY} installed!"
